### ISSUE TITLE
I got this, Unsupported format version '0.3' specified in module metadata. This version of Gradle supports format version 0.4 only

### ISSUE THREAD

**Issue by gros83** [netguru/Kissme#51]
Excuseme, I don´t write well.
> Could not resolve com.netguru.kissme:kissme-common:0.2.3.
      > Could not parse module metadata https://dl.bintray.com/netguru/maven/com/netguru/kissme/kissme-common/0.2.3/kissme-common-0.2.3.module
         > Unsupported format version '0.3' specified in module metadata. This version of Gradle supports format version 0.4 only.

**Comment by mkkroliks** [comment]
Same issue here.

**Comment by Tiska** [comment]
hello, this is a bug with gradle metadata incompatibility between gradle versions. Try to local build (./gradlew publishtoMavenLocal) with this branch upgraded : https://github.com/netguru/Kissme/pull/53

**Comment by samiuelson** [comment]
Solved by #57
